<a href="https://colab.research.google.com/github/devfajar/data_analysis_freecodecamp/blob/main/numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
# printing 10 zero
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
np.ones([2,2], dtype=np.int)

array([[1, 1],
       [1, 1]])

In [ ]:
np.ones([3, 2], dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
x = np.arange(4, dtype=np.int)

np.ones_like(x)

array([1, 1, 1, 1])

my answer

In [ ]:
x = np.zeros([2, 3], dtype=np.int)

x

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
x = np.array([[1,2,3], [4,5,6]], dtype=np.int)

np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

make matrix 4x4 filled with 5 

In [ ]:
np.ones([4,4], dtype=np.int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

**Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.**

In [ ]:
X = np.array([[2,3], [6, 2]], dtype=np.int)
np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

In [2]:
# diagonal matrix with ones and zeros else wehere
# my answer
x = np.ones((3, 3), dtype=np.int)
np.fill_diagonal(x, 0)
x

array([[0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [4]:
# real answer
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])